greeting:
  message: "hello"

quarkus:
  native:
    # if needed add -H:+UnlockExperimentalVMOptions
    additional-build-args: -H:IncludeResources=venus-sample-custom-function/fm-doc-process-config.xml,\
      -H:IncludeResources=venus-sample-custom-function/template/document.ftl